name: Publish to NPM

on:
        release:
                types: [published]
        workflow_dispatch:

jobs:
        publish:
                runs-on: ubuntu-latest

                steps:
                        - name: Checkout
                          uses: actions/checkout@v3
                          with:
                                  ref: ${{ github.head_ref }}
                                  fetch-depth: 0

                        - name: Setup node and restore cached dependencies
                          uses: actions/setup-node@v3
                          with:
                                  node-version: '22'
                                  registry-url: 'https://registry.npmjs.org/'
                                  cache: 'yarn'

                        - name: Install packages
                          run: yarn install --immutable

                        - name: Test
                          run: yarn test

                        - name: Build
                          run: yarn build

                        - name: Publish to NPM
                          run: yarn npm publish --access public --no-git-checks
                          env:
                                  NODE_AUTH_TOKEN: ${{ secrets.NODE_PUBLISH }}
