name: Publish to NPM

on:
        release:
                types: [published]
        workflow_dispatch:

jobs:
        publish:
                runs-on: ubuntu-latest
                permissions:
                    contents: write
                    id-token: write
                steps:
                        - name: Checkout
                          uses: actions/checkout@v4.2.0


                        - name: Setup node
                          uses: actions/setup-node@v4.0.4
                          with:
                                  node-version: 22
                                  registry-url: https://registry.npmjs.org/

                        - name: Install packages
                          run: npm install

                        - name: Test
                          run: npm run test

                        - name: Build
                          run: npm run build

                        - name: Publish to NPM
                          run: npm publish --access public --provenance
                          env:
                                  NODE_AUTH_TOKEN: ${{ secrets.NODE_PUBLISH }}
